# Generated by Django 3.2.22 on 2024-12-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID_User', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('User_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
