# Generated by Django 5.1.5 on 2025-01-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_weeklyreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('project', 'start_date', 'end_date')},
        ),
    ]
