# Generated by Django 5.1.5 on 2025-01-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_weeklyreport_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together=set(),
        ),
    ]
