# Generated by Django 5.1.4 on 2025-01-23 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_weeklyreport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='completion_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
